-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE FOOD_SAFETY;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.FARMS (
  FARM_ID VARCHAR(20) NOT NULL, FARM_NAME VARCHAR(200), PROVINCE VARCHAR(50), AREA_HA FLOAT, FARM_TYPE VARCHAR(30), CERTIFICATION VARCHAR(50), STATUS VARCHAR(20), ESTABLISHED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.BATCHES (
  BATCH_ID VARCHAR(30) NOT NULL, FARM_ID VARCHAR(20), BATCH_DATE DATE, PRODUCT VARCHAR(50), QUANTITY FLOAT, UNIT VARCHAR(20), QUALITY_GRADE VARCHAR(10), TEMPERATURE_C FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.INSPECTIONS (
  INSPECTION_ID VARCHAR(30) NOT NULL, BATCH_ID VARCHAR(30), INSPECTION_DATE TIMESTAMP, INSPECTOR_ID VARCHAR(20), TEST_TYPE VARCHAR(50), RESULT VARCHAR(20), SCORE FLOAT, NOTES VARCHAR(500), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.EXPORTS (
  EXPORT_ID VARCHAR(30) NOT NULL, BATCH_ID VARCHAR(30), DESTINATION VARCHAR(100), SHIP_DATE DATE, QUANTITY FLOAT, VALUE_USD FLOAT, CERTIFICATION VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
