-- Generated from generator/demo_specs/aws-thailand-food-safety.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-food-safety
-- This is the schema that is actually deployed for THAILAND_FOOD_SAFETY.

-- Alerts fire on the bottom tail of Safety Score (Avg)
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_SAFETY_SCORE_AVG) AS T
  FROM RAW.CCP_MONITORING
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_SAFETY_SCORE_AVG <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_SAFETY_SCORE_AVG), 2) AS AVG_SAFETY_SCORE,
  ROUND(AVG(f.KPI_TRACE_TO_SOURCE), 2) AS AVG_TRACE_TO_SOURCE,
  ROUND(AVG(f.KPI_BATCH_COVERAGE), 2) AS AVG_BATCH_COVERAGE
FROM RAW.CCP_MONITORING f
JOIN RAW.THAI_FOOD_INDUSTRY e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_SAFETY_SCORE_AVG), 2) AS AVG_SAFETY_SCORE,
  ROUND(AVG(f.KPI_TRACE_TO_SOURCE), 2) AS AVG_TRACE_TO_SOURCE,
  ROUND(AVG(f.KPI_BATCH_COVERAGE), 2) AS AVG_BATCH_COVERAGE
FROM RAW.CCP_MONITORING f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SAFETY_SCORE_AVG) AS KPI_SAFETY_SCORE_AVG, AVG(KPI_TRACE_TO_SOURCE) AS KPI_TRACE_TO_SOURCE, AVG(KPI_BATCH_COVERAGE) AS KPI_BATCH_COVERAGE FROM RAW.CCP_MONITORING),
     en AS (SELECT SUM(KPI_ACTIVE_RECALLS) AS KPI_ACTIVE_RECALLS, SUM(KPI_PENDING_AUDITS) AS KPI_PENDING_AUDITS, SUM(KPI_CERTIFIED_FACILITIES) AS KPI_CERTIFIED_FACILITIES, SUM(KPI_BLOCKCHAIN_RECORDS) AS KPI_BLOCKCHAIN_RECORDS FROM RAW.THAI_FOOD_INDUSTRY)
  SELECT 1 AS SORT_ORDER, 'Safety Score (Avg)' AS TITLE, KPI_SAFETY_SCORE_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SAFETY_SCORE_AVG), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Recalls' AS TITLE, KPI_ACTIVE_RECALLS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_RECALLS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Pending Audits' AS TITLE, KPI_PENDING_AUDITS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PENDING_AUDITS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Certified Facilities' AS TITLE, KPI_CERTIFIED_FACILITIES AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CERTIFIED_FACILITIES)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Trace-to-Source' AS TITLE, KPI_TRACE_TO_SOURCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TRACE_TO_SOURCE), 1) AS DECIMAL(38,1))) || ' ' || 'hrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Batch Coverage' AS TITLE, KPI_BATCH_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_BATCH_COVERAGE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Blockchain Records' AS TITLE, KPI_BLOCKCHAIN_RECORDS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_BLOCKCHAIN_RECORDS) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
