-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Food Safety & Quality Compliance
-- ============================================================================
USE DATABASE FOOD_SAFETY;
USE SCHEMA ML;

-- ML.FORECAST: CCP_DEVIATION_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CCP_DEVIATION_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CCP_DEVIATION_TRENDS'),
  SERIES_COLNAME => 'CCP_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.CCP_DEVIATION_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.CCP_DEVIATION_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: LAB_RESULT_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.LAB_RESULT_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CCP_DEVIATION_TRENDS'),
  SERIES_COLNAME => 'FACILITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.LAB_RESULT_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.LAB_RESULT_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CCP_DEVIATION_TRENDS'), SERIES_COLNAME => 'FACILITY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

