-- ============================================================================
-- 99_RESET.SQL — Reset Food Safety & Quality Compliance to clean demo state
-- ============================================================================
USE DATABASE FOOD_SAFETY;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_INSPECTIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_COMPLIANCE SUSPEND;
ALTER TASK IF EXISTS APP.TASK_CHECK_ALERTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.FACILITY_COMPLIANCE_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.CCP_DEVIATION_TRENDS REFRESH;
ALTER DYNAMIC TABLE CURATED.RECALL_RISK_INDEX REFRESH;
ALTER DYNAMIC TABLE CURATED.REGULATION_COMPLIANCE_GAP REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM FOOD_SAFETY.RAW.CCP_MONITORING → 500000
-- SELECT COUNT(*) FROM FOOD_SAFETY.RAW.INSPECTION_REPORTS → 680
-- SELECT COUNT(*) FROM FOOD_SAFETY.CURATED.FACILITY_COMPLIANCE_SCORE WHERE COMPLIANCE_RATE < 0.98 → 6

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_CHECK_ALERTS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_COMPLIANCE RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_INSPECTIONS RESUME;
